//Automatically generated by tools/AddPdfParam.py on 2019-07-19
#pragma once

#include"BasePdfParam.h"

/**
  @class Bernstein_PdfParam

  @brief A class for Bernstein pdf parameterisation

  ADD DESCRIPTION HERE

  @version 0.1                                                                                                                                               

  @date 2019-12-01       

*/


namespace xfitter{
class BernsteinPdfParam:public BasePdfParam{
  public:
    BernsteinPdfParam(const std::string&name):BasePdfParam(name){}
    virtual double operator()(double x)const override final;
    virtual void atStart()override final;
};
}
