#!/bin/bash

version=1.2
chaplin=chaplin-${version}
chaplinsrc=`ls $chaplin/src`

# download if necessary
if [[ x$chaplinsrc == x ]];
then
    rm -r chaplin-${version}
    wget https://chaplin.hepforge.org/code/chaplin-${version}.tar
    tar -xf chaplin-${version}.tar
    rm chaplin-${version}.tar
fi

cd ${chaplin}
./configure --prefix=`pwd`
make install
