Minimizer: MINUIT # CERES
MINUIT:
  Commands: |
    set str 2
    call fcn 1
    migrad
    call fcn 3

Parameters:
  Ag   : [0.57764, 0.30153E-01 ]
  Bg   : [0.75832, 0.33033 ]
  Cg   : [18.201, 3.4406 ]
#  Agp  : [ 0.07311, 0.01 ]  # negative gluon ....
#  Bgp  : [ -0.383100, 0.01 ]
#  Cgp  : [ 25.0, 0.]  # fix C of negative gluon
  Aup  :  [1.1129, 0.24817E-01]
  Bup  : [ -0.61516, 0.65898E-01 ]
  Cup  : [1.7440, 0.50931E-01 ]
  Dup  : [  8.3739, 1.4510    ]
  Eup  : [5.4802, 0.36971 ]
  Adp  :  [1.011, 0.36971 ] #DEPENDENT
  ASp  :  [0.32190, 0.65982E-01]
  BSp  :  [1.2649, 0.56029]
  CSp  :  [9.8777, 0.96283]
  ACp  :  [0.74251, 0.15467E-01]
  BCp  :  [-0.85582, 0.43079E-01]
  CCp  :  [4.8765, 0.21439]
  ABp  :  [0.70023, 0.15502E-01]
  BBp  :  [-0.43202, 0.50529E-01]
  CBp  :  [4.0749, 0.25233]
  DBp  :  [12.069, 1.9937]
  EBp  :  [8.1823, 0.45166]
  ZERO : [ 0. ]          # zero

Parameterisations:
  par_up:
    class: Pion_FF
    parameters: [Aup,Bup,Cup,Dup,Eup]
#  par_dp:
#    class: Pion_FF
#    parameters: [Adv,Bdv,Cdv]
  par_cp:
    class: Pion_FF
    parameters: [ACp,BCp,CCp]
  par_bp:
    class: Pion_FF
    parameters: [ABp,BBp,CBp, DBp, EBp]
  par_sp: # s=fs/(1-fs) * Dbar
    class: Pion_FF
    parameters: [ASp,BSp,CSp]
  par_g:
    class: Pion_FF
    parameters: [Ag,Bg,Cg]
  #par_s:
    #class: HERAPDF
    #parameters: [As,Bs,Cs]
  #par_s:
    #class: Expression
    #expression: "Adbar*fs/(1-fs)*(x^Bdbar*(1-x)^Cdbar)"
  # Another example for Expression parameterisation
  #par_g:
    #class: Expression
    #expression: "Ag*(x^Bg*(1-x)^Cg-Agp*x^Bgp*(1-x)^Cgp)"

DefaultDecomposition: Pion_FF_B_C
Decompositions:
  Pion_FF_B_C: #proton:
    class: Pion_FF_BC
    xup: par_up
#    xdp: par_dp
    xcp: par_cp
    xbp: par_bp
    xsp: par_sp
    xg: par_g

DefaultEvolution: proton-APFELff
#DefaultEvolution: proton-APFELff
#DefaultEvolution: proton-QCDNUM
#DefaultEvolution: proton-LHAPDF

Evolutions:
  #APFELxx:
  #  ? !include evolutions/APFELxx.yaml
  #  decomposition: Pion_FF_B_C
  proton-APFELff:
    ? !include evolutions/APFEL.yaml
    decomposition: Pion_FF_B_C
  #proton-QCDNUM:
   # ? !include evolutions/QCDNUM.yaml
   # decomposition: proton #this could be omitted, as the default decomposition is set
    # The following allows QCDNUM to read PDFs from other evolutions:
    #EvolutionCopy: "proton-LHAPDF"
 # proton-LHAPDF:
  #  class: LHAPDF
 #   set: "NNPDF30_nlo_as_0118"
    #set: "CT10nlo"
 #   member: 0
#  proton-APFEL:
#    ? !include evolutions/APFELxx.yaml
#    decomposition: proton
 # antiproton:
  #  class: FlipCharge
    #input: proton-QCDNUM
 #   input: proton-LHAPDF
#  neutron:
#    class: FlipUD
#    input: proton-QCDNUM

Q0 : 1.378404875209 # Initial scale =sqrt(1.9)

? !include constants.yaml


# QCD parameters
Order: NLO
NFlavour: 5
isFFNS: 0

# the two parameters below are not used: why one needs them with the present setup?
Q0 : 1.378404875209 # Initial scale =sqrt(1.9) 
alphas : 0.118

byReaction:
  # RT DIS scheme settings:
  RT_DISNC:
    ? !include reactions/RT_DISNC.yaml
    evolution: proton
  BaseDISCC:
    # BaseDISCC works only with QCDNUM evolution, need to specify it explicitly (in this case it is copied from LHAPDF, while default evloution is LHAPDF)
    evolution: proton
  # FONLL scheme settings:
  FONLL_DISNC:
    ? !include reactions/FONLL_DISNC.yaml
  FONLL_DISCC:
    ? !include reactions/FONLL_DISCC.yaml
  # FF ABM scheme settings:
  FFABM_DISNC:
    ? !include reactions/FFABM_DISNC.yaml
  FFABM_DISCC:
    ? !include reactions/FFABM_DISCC.yaml
  # AFB settings:
  AFB:
    ? !include reactions/AFB.yaml
  # APPLgrid settings:
  APPLgrid:
    ? !include reactions/APPLgrid.yaml
  # (optional) Fractal module settings:
  Fractal_DISNC:
    ? !include reactions/Fractal_DISNC.yaml

# Specify HF scheme used for DIS NC processes:
hf_scheme_DISNC :
  defaultValue : 'NC_SIA'   


OutputDirectory: "output" #Can be omitted, default is "output"

WriteLHAPDF6:
  name: "proton"
  description: "..."
  authors: "..."
  reference: "..."
    # use DefaultEvolution
  #evolution: proton-QCDNUM
    # take internal grid
  preferInternalGrid:
    # or define grid
  #Xrange: [1e-4, 1]
  #Qrange: [1,1000]
  #Xnpoints: 200
  #Qnpoints: 120
