#
# Test file to illustrate how parameters can be transferred
#

# include : test.yaml  # Can include any file

Mz : 91.1876
Mw : 80.385
sin2thW : 
  value : 0.23127
  step  : 0.02

Order : NNLO
NFlavour : 5

mch : 1.43 
mbt : 4.5


# Optimal RT scheme:
RT_DISNC:               # Reaction-specific settings
  varin : [0.0, 1.0, -0.666666666667, 1.0]

# speficify HF scheme:
hf_scheme_DISNC : 
  value : 'RT_DISNC'
#  'HERA1+2 NCep 920' : 'BaseDISNC'
#  1 : BaseDISNC  

# We want to fit alphaS, making this explicitly:
AalphaS: 
  value: 20.0
  step:  0.0
  prior: 20.0  
  priorUnc: 0.1
  min: 19.0
  max: 21.0


APPLgrid:  # APPLgrid specific
  muF: 1.0
  muR: 1.0
  Order : NLO   # APPLgrids are at max. NLO for now

# Example of vectors

testVec :  [1., 2., 3., 4.]
