#Minimizers : [CERES, MINUIT]
Minimizers : [CERES]
#Minimizers : [MINUIT]

CERES:
  offset: 2
  tolerance: 1e-5
  strategy: 0
  covariance: 0
  threads: 2

MINUIT:
  Commands: |
    set str 2
    call fcn 3
#    migrad 5000 1000
#  doErrors :  Pumplin
#  threads: 30

Parameters:
  Ag   :  DEPENDENT
  Bg   : [ -0.146429,    0.013969  ]
  Cg   : [  0.656877,    0.135395  ]
  Agp  : [  0.027570,    0.000750  ]  # negative gluon
  Bgp  : [ -0.446945,    0.011025  ]
  Cgp  : [ 25.0,      0.    ]  # fix C of negative gluon
  Auv  :  DEPENDENT
  Buv  : [  0.634950,    0.003617 ]
  Cuv  : [  3.423164,    0.029478  ]
  Euv  : [ 14.056613,    0.209229   ]
  Adv  :  DEPENDENT
  Bdv  : [  0.843569,    0.016835  ]
  Cdv  : [  2.737593,    0.111268   ]
  CUbar: [  6.207219,    0.214009   ]
  DUbar: [  2.548959,    0.183562   ]
  ADbar: [  0.244221,    0.001091  ]
  BDbar: [ -0.149572,    0.002588 ]
  CDbar: [  6.207219,    0.526551]
  ZERO : [ 0. ]          # zero
  fs   : [ 0.4, 0.0 ]
  fd   : "=1-fs"
  AUbar: "=(1-fs)*ADbar"

Parameterisations:
  par_uv:
    class: HERAPDF
    parameters: [Auv,Buv,Cuv,ZERO,Euv]
  par_dv:
    class: HERAPDF
    parameters: [Adv,Bdv,Cdv]
  par_Ubar: # = ubar
    class: HERAPDF
    parameters: [AUbar,BDbar,CUbar,DUbar]
  par_Dbar: # = dbar + sbar
    class: HERAPDF
    parameters: [ADbar,BDbar,CDbar]
  par_dbar: # = (1-fs) Dbar
    class: Factor
    input: par_Dbar
    factor: fd
  par_s: # = sbar = fs Dbar
    class: Factor
    input: par_Dbar
    factor: fs
  par_g:
    class: NegativeGluon
    parameters: [Ag,Bg,Cg,ZERO,ZERO,Agp,Bgp,Cgp]

DefaultDecomposition: proton
Decompositions:
  proton:
    class: UvDvUbarDbarS
    # Note that HERAPDF parameterises Ubar and Dbar,
    # but this decomposition uses ubar and dbar
    xuv: par_uv
    xdv: par_dv
    xubar: par_Ubar
    xdbar: par_dbar
    xs: par_s
    xg: par_g

DefaultEvolution: proton-QCDNUM
     
Evolutions:
  proton-QCDNUM:
    ? !include evolutions/QCDNUM.yaml
    decomposition: proton #this could be omitted, as the default decomposition is set
    # The following allows QCDNUM to read PDFs from other evolutions:
    EvolutionCopy: "proton-PBTMD"
  proton-PBTMD:
    class: PBTMD

# QCD parameters
Order: NLO
NFlavour: 5
isFFNS: 0
Q0 : 1.18 # Initial scale =sqrt(1.9)
alphas : 0.118
? !include constants.yaml



byReaction:
  # RT DIS scheme settings:
  RT_DISNC:
    ? !include reactions/RT_DISNC.yaml

# Specify HF scheme used for DIS NC processes:
hf_scheme_DISNC :
  defaultValue : 'RT_DISNC'        # global specification

# Specify HF scheme used for DIS CC processes:
hf_scheme_DISCC :
  defaultValue : 'BaseDISCC'       # global specification

WriteLHAPDF6:
  name: "PBNLO-2.5.12-EWK-04-Set2-Q0ord=0.000001-Polarization_0_enhance-fit"
  description: "..."
  authors: "..."
  reference: "..."
    # use DefaultEvolution
  evolution: proton-PBTMD
    # take internal grid
  preferInternalGrid:
    # or define grid
  #Xrange: [1e-4, 1]
  #Qrange: [1,1000]
  Xnpoints: 20
  Qnpoints: 20
