Minimizer: MINUIT
MINUIT:
  Commands: |
    set str 2
    call fcn 3

Evolutions:
  proton-LHAPDF:
    class: LHAPDF
    set: "MMHT2014nnlo68cl"
    member: 0

DefaultEvolution: proton-LHAPDF

Q0 : 1.378404875209 # Initial scale =sqrt(1.9)

? !include constants.yaml

alphas : 0.118

byReaction:
  Hathor:
     MS_MASS: 1
     muR: 1.
     muF: 1.
     RATIO: 0

OutputDirectory: "output" #Can be omitted, default is "output"
