//Automatically generated by ./tools/AddEvolution.py on 2018-12-25
#pragma once
#include"BaseEvolution.h"

namespace xfitter{
/**
  @class FlipChargeEvol

  @brief A class for FlipCharge modifier evolution

  Takes as input another evolution and switches each quark with antiquark.
  This turns a particle into an antiparticle.

  In YAML configuration, provide another evolution's name as "input"
*/
class FlipChargeEvol:public BaseEvolution{
  public:
    FlipChargeEvol(const char*name):BaseEvolution(name){}
    virtual const char*getClassName()const override final{return"FlipCharge";};
    virtual void atStart()override final;
    virtual void atConfigurationChange()override final;
    virtual std::map<int,double>xfxQmap(double x,double Q)override final;
    virtual double xfxQ(int i,double x,double Q)override final;
    virtual void xfxQarray(double x,double Q,double*pdfs)override final;
    virtual double getAlphaS(double Q)override final;
    virtual std::vector<double> getXgrid() override final;
    virtual std::vector<double> getQgrid() override final;
  private:
    BaseEvolution*input;
};
}
