Minimizer: MINUIT # CERES
MINUIT:
  Commands: |
    set str 2
    call fcn 3

DefaultEvolution: proton-LHAPDF

Evolutions:
  proton-LHAPDF:
    class: LHAPDF
    set: "NNPDF30_nlo_as_0118"
    member: 0

# QCD parameters
Order: NLO
NFlavour: 5
isFFNS: 0

? !include constants.yaml

byReaction:
  # AFB settings:
  AFB:
    ? !include reactions/AFB.yaml

