Minimizer: MINUIT
MINUIT:
  Commands: |
    set str 2
    call fcn 3

Parameters:
  Auv : [ 1.00000000, 0.00000000 ]
  Buv : [ 0.63144863, 0.02954405 ]
  Cuv : [ 4.84372279, 0.07646111 ]
  Duv : [ 0.00000000, 0.00000000 ]
  Euv : [ 17.47194527, 2.32145176 ]
  Adv : [ 1.00000000, 0.00000000 ]
  Bdv : [ 0.86165329, 0.06991674 ]
  Cdv : [ 4.44612054, 0.32714862 ]
  Ddv : [ 0.00000000, 0.00000000 ]
  Edv : [ 0.00000000, 0.00000000 ]
  Cubar : [ 7.61261199, 0.73394704 ]
  Dubar : [ 14.14712803, 2.85946815 ]
  Eubar : [ 0.00000000, 0.00000000 ]
  Adbar : [ 0.09408433, 0.00506237 ]
  Bdbar : [ -0.17987840, 0.00618488 ]
  Cdbar : [ 16.01409431, 3.86861456 ]
  Ddbar : [ 0.00000000, 0.00000000 ]
  Edbar : [ 0.00000000, 0.00000000 ]
  As : [ 0.07214400, 0.00000000 ]
  ZERO : [ 0.00000000, 0.00000000 ]
  BG_g_A : [ 1.00000000, 0.00000000 ]
  BG_g_B : [ 0.06463887, 0.05984238 ]
  BG_g_C : [ 7.12186012, 0.38089485 ]
  BG_g_F : [ 0.07917094, 0.02253926 ]
  BG_g_G : [ 0.00000000, 0.00000000 ]
  BG_g_H : [ 0.00000000, 0.00000000 ]


Parameterisations:
  par_s:
    class: Expression
    expression: "Adbar*fs/(1-fs)*(x^Bdbar*(1-x)^Cdbar)"
  par_g:
    class: Expression
    expression: "BG_g_A * x^BG_g_B * (1 - x)^BG_g_C * (1 + BG_g_F * ln(x) + BG_g_G * ln(x)^2 + BG_g_H * ln(x)^3)"
  par_uv:
    class: Expression
    expression: "Auv*(x^Buv*(1-x)^Cuv)*(1+Duv*x+Euv*x^2)"
  par_dv:
    class: Expression
    expression: "Adv*(x^Bdv*(1-x)^Cdv)*(1+Ddv*x+Edv*x^2)"
  par_ubar:
    class: Expression
    expression: "Adbar*(x^Bdbar*(1-x)^Cubar)*(1+Dubar*x+Eubar*x^2)"
  par_dbar:
    class: Expression
    expression: "Adbar*(x^Bdbar*(1-x)^Cdbar)*(1+Ddbar*x+Edbar*x^2)"

DefaultDecomposition: proton
Decompositions:
  proton:
    class: UvDvUbarDbarS
    xuv: par_uv
    xdv: par_dv
    xubar: par_ubar
    xdbar: par_dbar
    xs: par_s
    xg: par_g

DefaultEvolution: proton-APFELff

Evolutions:
  proton-APFELff:
    ? !include evolutions/APFEL.yaml
    class : APFEL
    theoryType : "QCD"  # or QUniD
    xGrid   :  [9.9e-9, 0.01, 0.7]
    nxGrid  :  [40, 30, 20]
    SplineOrder : 2
    #qLimits : [1.0, 10000.0]
    qLimits : [0.89, 15000.0]
    heavyQuarkMassScheme : "Pole" # or "MSBar"
    heavyQuarkMassRunning : "Off" # or "On"
    nllxResummation : "Off" # or "On"
    FONLLVariant : "B"
    muRoverQ : 1.0
    muFoverQ : 1.0
    #kmc : 2.2
    #kmb : 2.2
    #kmc : 3.1
    #kmb : 3.1
    kmc : 4.5
    kmb : 4.5
    #kmc : 6.0
    #kmb : 6.0
    #kmc : 10.0
    #kmb : 10.0
    kmt : 1.0

# QCD parameters
Order: NLO
NFlavour: 5
Q0 : 1.378404875209 # Initial scale =sqrt(1.9)
# AlphaS, incuding options to fit it:
alphas: 0.118
#  value: 0.118
#  step:  0.01
#  prior: 0.118
#  priorUnc: 0.1
#  min: 0.1
#  max: 0.3

? !include constants.yaml



# Strange and charm fractions:
fs: 0.4
fcharm: 0.

# Specify HF scheme used for DIS NC processes:
hf_scheme_DISNC :
  defaultValue : 'FONLL_DISNC'     # global specification

# Specify HF scheme used for DIS CC processes:
hf_scheme_DISCC :
  defaultValue : 'FONLL_DISCC'     # global specification

byReaction:
  # FONLL scheme settings:
  FONLL_DISNC:
    ? !include reactions/FONLL_DISNC.yaml
  FONLL_DISCC:
    ? !include reactions/FONLL_DISCC.yaml
  cbdiff:
    #debug: 1
    MS_MASS: 0
    precision: 0.65
    FragPar: 4.4 # charm
    hadronMass: 1.5 # charm
    mf_A: 1.0
    mf_B: 4.0
    mr_A: 1.0
    mr_B: 4.0
    steer_nf: 4 # nf = 3 in charm data because of pT cut
