	CCards.Create("QCD_order", 1);

	CCards.Create("nFlavors", 0);
	CCards.Create("Par_Model", 0);
	CCards.Create("DumpFactor", 0.01);
	CCards.Create("Pion_order", 0);
	CCards.Create("Mass_corr", 0);
	CCards.Create("MaxFlavor", 6);
	CCards.Create("QQ_start", 2.0);
	CCards.Create("QQ_min", 1.8);
	CCards.Create("QQ_max", 1e5);
	CCards.Create("QQ_factor", sqrt(2.));

	//CCards.Create("Lambda_4", 0.2);
	CCards.Create("alphas_RG", 1);
	CCards.Create("alphas", 0.118);
	// CCards.Create("alphas_scale", MASS_Z0);

	// CCards.Create("c_mass", MASS_C);
	// CCards.Create("b_mass", MASS_B);
	// CCards.Create("t_mass", MASS_T);

	CCards.Create("x_min", 1e-5);
	CCards.Create("x_points", 280);
	// CCards.Create("x_scl_mode", xgrid_t::LOGLIN);
	CCards.Create("x_par", 0.1);

	CCards.Create("Scale_exponent", 1);
	CCards.Create("Integ_accuracy", 1e-6);

	CCards.Create("ExpData", "");
	CCards.Create("Exp_scale", 1.0);
	CCards.Create("Exp_QQmin", 0.0);
	CCards.Create("Exp_zmax", 1.0);
	CCards.Create("Exp_s", 101200.0);
	CCards.Create("ExpData2", "<none>");
	CCards.Create("Exp_scale2", 0.0);
	CCards.Create("Err_syst", 999);
	CCards.Create("Err_cor_scl", 1.0);
	CCards.Create("Pomeron_tslope", 7.2);

	CCards.Create("Tw4_QQ0", 1.0);

