if(NOT QCDNUM_FOUND)
  message(STATUS "Skipping optional reaction FFABM_DISCC because QCDNUM library was not found")
  return()
endif()

set(TARGET reactionFFABM_DISCC)
#add_library(${TARGET} MODULE ReactionFFABM_DISCC.cc)
#add_library(${TARGET} MODULE ReactionFFABM_DISCC.cc numufcalflux1.F)
add_library(${TARGET} MODULE ReactionFFABM_DISCC.cc numufcalflux1.F nuke_fast.F)
#target_link_libraries(${TARGET} PRIVATE xfitter reactionBaseDISCC ABM)
#target_link_libraries(${TARGET} PRIVATE xfitter reactionBaseDISCC ABM GSL)
#target_link_libraries(${TARGET} PRIVATE xfitter reactionBaseDISCC ABM GSL cuba)
target_link_libraries(${TARGET} PRIVATE xfitter reactionBaseDISCC ABM GSL cuba)
install(TARGETS ${TARGET} DESTINATION ${DEST_MODULE})
install(FILES FFABM_DISCC.yaml DESTINATION ${DEST_YAML}/reactions)
