#if(NOT QCDNUM_FOUND)
#  message(STATUS "Skipping optional reaction FFABM_DISNC because QCDNUM library was not found")
#  return()
#endif()

set(TARGET reactionBaseFFABM)
add_library(${TARGET} SHARED ReactionBaseFFABM.cc)
target_link_libraries(${TARGET} PRIVATE xfitter ABM)
target_include_directories(${TARGET} PUBLIC .)
install(TARGETS ${TARGET} DESTINATION ${DEST_MODULE})
#install(FILES BaseFFABM.yaml DESTINATION ${DEST_YAML}/reactions)
