Minimizer: MINUIT 
MINUIT:
  Commands: |
    call fcn 1
    set str 2
    call fcn 3

Parameters:
  Ag   :  DEPENDENT
  Bg   : [ -0.061953, 0.27 ]
  Cg   : [  5.562367,  0.32 ]
  Agp  : [ 0.166087, 0.01 ]  # negative gluon ....
  Bgp  : [ -0.383100, 0.01 ]
  Cgp  : [ 25.0, 0.]  # fix C of negative gluon
  Auv  :  DEPENDENT
  Buv  : [ 0.810476, 0.016 ]
  Cuv  : [ 4.823512, 0.06 ]
  Duv  : [    0     ]
  Euv  : [ 9.921366, 0.8 ]
  Adv  :  DEPENDENT
  Bdv  : [ 1.029995, 0.06 ]
  Cdv  : [ 4.846279, 0.3 ]
  Aubar: [ 0.0, 0.0 ] # not used (Aubar=Adbar)
  Bubar: [ 0.0, 0.0  ] # not used (Bubar=Bdbar)
  Cubar: [ 7.059694, 0.8 ]
  Dubar: [ 1.548098, 1.0 ]
  Adbar: [ 0.1613, 0.01 ]
  Bdbar: [ -0.1273, 0.004  ]
  Cdbar: # another example of providing value, step etc.
    value: 9.586246
    step: 1.2345
  ZERO : [ 0. ]          # zero
  fs   :   0.4   #no step means fixed
  DbarToS: "=fs/(1-fs)"

Parameterisations:
  par_uv:
    class: HERAPDF
    parameters: [Auv,Buv,Cuv,Duv,Euv]
  par_dv:
    class: HERAPDF
    parameters: [Adv,Bdv,Cdv]
  par_ubar:
    class: HERAPDF
    parameters: [Adbar,Bdbar,Cubar,Dubar]
  par_dbar:
    class: HERAPDF
    parameters: [Adbar,Bdbar,Cdbar]
  par_s: # s=fs/(1-fs) * Dbar
    class: Factor
    factor: DbarToS #name of parameter
    input: par_dbar
  par_g:
    class: NegativeGluon
    parameters: [Ag,Bg,Cg,ZERO,ZERO,Agp,Bgp,Cgp]

DefaultDecomposition: proton
Decompositions:
  proton:
    class: UvDvUbarDbarS
    xuv: par_uv
    xdv: par_dv
    xubar: par_ubar
    xdbar: par_dbar
    xs: par_s
    xg: par_g

DefaultEvolution: proton-APFELff

Evolutions:
  proton-APFELff:
    ? !include evolutions/APFEL.yaml
    decomposition: proton

# QCD parameters
Order: NNLO
NFlavour: 4
isFFNS: 1 # 0 (default): VFNS with number of flavours changing from 3 to NFlavour, 1: FFNS with number of flavours = NFlavour at any scale
alphas : 0.118
Q0 : 1.378404875209 # Initial scale =sqrt(1.9)

? !include constants.yaml

byReaction:
  # FONLL scheme settings:
  FONLL_DISNC:
    ? !include reactions/FONLL_DISNC.yaml
  FONLL_DISCC:
    ? !include reactions/FONLL_DISCC.yaml

# Specify HF scheme used for DIS NC processes:
hf_scheme_DISNC :
  defaultValue : 'FONLL_DISNC'     # global specification

# Specify HF scheme used for DIS CC processes:
hf_scheme_DISCC :
  defaultValue : 'FONLL_DISCC'     # global specification

OutputDirectory: "output" #Can be omitted, default is "output"

WriteLHAPDF6:
  name: "proton"
  description: "..."
  authors: "..."
  reference: "..."
    # use DefaultEvolution
  #evolution: proton-QCDNUM
    # take internal grid
  preferInternalGrid:
    # or define grid
  #Xrange: [1e-4, 1]
  #Qrange: [1,1000]
  #Xnpoints: 200
  #Qnpoints: 120
