Minimizer: MINUIT
MINUIT:
  Commands: |
    set str 2
    call fcn 3

Parameters:
  alphas : [0.118, 0.0]

  # mtp    : [172.5, 0.2]
  # deltamt: "=mtp-172.5"

  c1   : [3.0, 0.1]
  c2   : [-2.0, 0.1]
  c3   : [4.0, 0.0]

  
DefaultEvolution: proton-LHAPDF-nnpdf31

Evolutions:
  proton-LHAPDF-nnpdf31:
    class: LHAPDF
    set: "NNPDF31_nnlo_as_0118"
    member: 0
  proton-LHAPDF-ct14:
    class: LHAPDF
    set: "CT14nnlo"
    member: 0

# QCD parameters
Order: NNLO
NFlavour: 5
isFFNS: 0

? !include constants.yaml

byReaction:
  Hathor:
    ? !include reactions/Hathor.yaml
