#Minimizer: MINUIT
#MINUIT:
#  Commands: |
#    set str 2
#    call fcn 3
#    #migrad 10000

Minimizer: CERES

CERES:
  offset: 2
  tolerance: 1e-5
  strategy: 0
  covariance: 1

Parameters:
  Adbar: [ 0.091855, 0.009200 ]
  Agp: [ 4.346536, 1.770509 ]
  Bdbar: [ -0.206039, 0.015100 ]
  Bdv: [ 0.927002, 0.077950 ]
  Bg: [ -0.126292, 0.037906 ]
  Bgp: [ 0.098213, 0.066198 ]
  Buv: [ 0.765780, 0.026367 ]
  Cdbar: [ 5.286205, 1.273760 ]
  Cdv: [ 4.555094, 0.303116 ]
  Cg: [ 6.799477, 0.922559 ]
  Cubar: [ 6.888716, 1.348560 ]
  Cuv: [ 4.854042, 0.068817 ]
  Dubar: [ 6.233717, 3.540699 ]
  Euv: [ 11.817940, 1.494857 ]
  Ag   :  DEPENDENT
  Auv  :  DEPENDENT
  Duv  : [    0     ]
  Adv  :  DEPENDENT
  ZERO : [ 0. ]          # zero
  Cgp  : [ 25.0, 0.]  # fix C of negative gluon
  fs : [ 0.4, 0.0 ]

Parameterisations:
  par_uv:
    class: HERAPDF
    parameters: [Auv,Buv,Cuv,Duv,Euv]
  par_dv:
    class: HERAPDF
    parameters: [Adv,Bdv,Cdv]
  par_ubar:
    class: HERAPDF
    parameters: [Adbar,Bdbar,Cubar,Dubar]
  par_dbar:
    class: HERAPDF
    parameters: [Adbar,Bdbar,Cdbar]
  par_s:
    #class: HERAPDF
    #parameters: [As,Bs,Cs]
    # parametrise as expression: otherwise how to parametrise it as fs/(1-fs)*par_dbar using HERAPDF?
    class: Expression
    expression: "Adbar*fs/(1-fs)*(x^Bdbar*(1-x)^Cdbar)"
  par_g:
    class: NegativeGluon
    parameters: [Ag,Bg,Cg,ZERO,ZERO,Agp,Bgp,Cgp]

DefaultDecomposition: proton
Decompositions:
  proton:
    class: UvDvUbarDbarS
    xuv: par_uv
    xdv: par_dv
    xubar: par_ubar
    xdbar: par_dbar
    xs: par_s
    xg: par_g

#DefaultEvolution: proton-QCDNUM
#DefaultEvolution: proton-APFELff
DefaultEvolution: proton-APFELxx

Evolutions:
  #proton-APFELff:
  #  ? !include evolutions/APFEL.yaml
  #  decomposition: proton
  #proton-QCDNUM:
  #  ? !include evolutions/QCDNUM.yaml
  #  decomposition: proton #this could be omitted, as the default decomposition is set
  proton-APFELxx:
    ? !include evolutions/APFELxx.yaml
    decomposition: proton

# QCD parameters
Order: NNNLO
NFlavour: 5
isFFNS: 0
Q0 : 1.378404875209 # Initial scale =sqrt(1.9)
alphas : 0.118

? !include constants.yaml



byReaction:
  # FONLL scheme settings:
  FONLL_DISNC:
    ? !include reactions/FONLL_DISNC.yaml
  FONLL_DISCC:
    ? !include reactions/FONLL_DISCC.yaml
  N3LO_DISCC:
    ? !include reactions/N3LO_DISCC.yaml
    xGrid: [[100, 1e-5, 3], [60, 1e-1, 3], [50, 6e-1, 3], [50, 8e-1, 3]]
  N3LO_DISNC:
    ? !include reactions/N3LO_DISNC.yaml

# Specify HF scheme used for DIS NC processes:
hf_scheme_DISNC :
  #defaultValue : 'FONLL_DISNC'     # global specification
  defaultValue : 'N3LO_DISNC'     # global specification

# Specify HF scheme used for DIS CC processes:
hf_scheme_DISCC :
  #defaultValue : 'FONLL_DISCC'     # global specification
  defaultValue : 'N3LO_DISCC'     # global specification

WriteLHAPDF6:
  name: "proton"
  description: "..."
  authors: "..."
  reference: "..."
    # use DefaultEvolution
  #evolution: proton-QCDNUM
    # take internal grid
  preferInternalGrid:
    # or define grid
  #Xrange: [1e-4, 1]
  #Qrange: [1,1000]
  #Xnpoints: 200
  #Qnpoints: 120
