Minimizer: MINUIT
MINUIT:
  Commands: |
    set str 2

DefaultEvolution: proton-QCDNUM

Evolutions:
  proton-QCDNUM:
    ? !include evolutions/QCDNUM.yaml
    decomposition: proton #this could be omitted, as the default decomposition is set
    # The following allows QCDNUM to read PDFs from other evolutions:
    EvolutionCopy: "proton-LHAPDF"
  proton-LHAPDF:
    class: LHAPDF
    set: "NNPDF30_nlo_as_0118"
    member: 0

Q0 : 1.378404875209 # Initial scale =sqrt(1.9)

? !include constants.yaml

alphas : 0.118

byReaction:
  # RT DIS scheme settings:
  RT_DISNC:
    ? !include reactions/RT_DISNC.yaml

# Specify HF scheme used for DIS NC processes:
hf_scheme_DISNC :
  defaultValue : 'RT_DISNC'        # global specification

# Specify HF scheme used for DIS CC processes:
hf_scheme_DISCC :
  defaultValue : 'BaseDISCC'       # global specification

#
# Profiler allows to add variations of parameters and PDF eigenvectors as additional nuisance parameters
#
Profiler:
  #Parameters:
  #  alphas: [ 0.118, 0.119, 0.117 ]  # central, up, (down) variation. If down is not given, uses symmetrizes Up variation 
  Evolutions:
    proton-LHAPDF:
      sets:    [NNPDF30_nlo_as_0118]
      members: [[0,1,99]] # skip last replica because difference between 0 and 100 is linear combination of differences between 0 and 1-99 members
  Status: "On"               # "Off" to turn off profiler
  WriteTheo: "On"            # Can be "Off", "On" or "Asymmetric" (to store asymmetric variations)
  getChi2: "Off"              # determine and report chi2 for each variation
  enableExternalProfiler: "On" # enable creation of additional files, needed for xfitter draw
