Minimizer: MINUIT # CERES
MINUIT:
  Commands: |
    set str 2
    call fcn 1
    migrad
    call fcn 3
    
  doErrors :  Hesse # None

Parameters:
  Ag : [ 1.00000000, 0.00000000 ]
  Agp : [ 0.16751583, 0.01374756 ]
  Bg : [ -0.06259990, 0.02046388 ]
  Cg : [ 5.55406009, 0.30548916 ]
  Duv : [ 0.00000000, 0.00000000 ]
  Buv : [ 0.81077351, 0.01553414 ]
  Bgp : [ -0.38249475, 0.01016472 ]
  Cgp : [ 25.00000000, 0.00000000 ]
  Euv : [ 9.90725354, 0.81247008 ]
  Auv : [ 1.00000000, 0.00000000 ]
  Cuv : [ 4.82324868, 0.06309405 ]
  Adv : [ 1.00000000, 0.00000000 ]
  Aubar : [ 0.16130000, 0.00000000 ]
  Bdv : [ 1.03015347, 0.06078129 ]
  Cdv : [ 4.84667091, 0.29433410 ]
  Bubar : [ -0.12730000, 0.00000000 ]
  Cubar : [ 7.04306971, 0.79809932 ]
  Dubar : [ 1.51341566, 1.08122915 ]
  Adbar : [ 0.16132089, 0.00472137 ]
  Bdbar : [ -0.12727344, 0.00354001 ]
  Cdbar: # another example of providing value, step etc.
    value: 9.58732874
    step: 1.47520864
    #min
    #max
    #pr_mean
    #pr_sigma
  ZERO : [ 0.00000000, 0.00000000 ]
  fs : [ 0.40000000, 0.00000000 ]
  alphas : [0.118, 0.001]

Parameterisations:
  par_uv:
    class: HERAPDF
    parameters: [Auv,Buv,Cuv,Duv,Euv]
  par_dv:
    class: HERAPDF
    parameters: [Adv,Bdv,Cdv]
  par_ubar:
    class: HERAPDF
    parameters: [Adbar,Bdbar,Cubar,Dubar]
  par_dbar:
    class: HERAPDF
    parameters: [Adbar,Bdbar,Cdbar]
  par_s:
    #class: HERAPDF
    #parameters: [As,Bs,Cs]
    # parametrise as expression: otherwise how to parametrise it as fs/(1-fs)*par_dbar using HERAPDF?
    class: Expression
    expression: "Adbar*fs/(1-fs)*(x^Bdbar*(1-x)^Cdbar)"
  par_g:
    class: NegativeGluon
    parameters: [Ag,Bg,Cg,ZERO,ZERO,Agp,Bgp,Cgp]

DefaultDecomposition: proton
Decompositions:
  proton:
    class: UvDvUbarDbarS
    xuv: par_uv
    xdv: par_dv
    xubar: par_ubar
    xdbar: par_dbar
    xs: par_s
    xg: par_g

DefaultEvolution: proton-QCDNUM

Evolutions:
  proton-QCDNUM:
    ? !include evolutions/QCDNUM.yaml
    decomposition: proton #this could be omitted, as the default decomposition is set

# QCD parameters
Order: NNLO
NFlavour: 5
isFFNS: 0
Q0 : 1.378404875209 # Initial scale =sqrt(1.9)

? !include constants.yaml

# Specify HF scheme used for DIS NC processes:
hf_scheme_DISNC :
  defaultValue : 'BaseDISNC'       # global specification

# Specify HF scheme used for DIS CC processes:
hf_scheme_DISCC :
  defaultValue : 'BaseDISCC'       # global specification

WriteLHAPDF6:
  name: "proton"
  description: "..."
  authors: "..."
  reference: "..."
    # use DefaultEvolution
  #evolution: proton-QCDNUM
    # take internal grid
  preferInternalGrid:
    # or define grid
  #Xrange: [1e-4, 1]
  #Qrange: [1,1000]
  #Xnpoints: 200
  #Qnpoints: 120
