Minimizer: MINUIT
MINUIT:
  Commands: |
    set str 2
    call fcn 3

Parameters:
  Ag   :  DEPENDENT
  Bg   : [ 0.023513, 0.08 ]
  Cg   : [ 11.595993,  1.62 ]
  Eg   : [ 16.634623,  11.5 ]
  Agp  : [ 0.029088, 0.01 ]  # negative gluon
  Bgp  : [ -0.340250, 0.13 ]
  Cgp  : [ 25.0, 0.]  # fix C of negative gluon
  Auv  :  DEPENDENT
  Buv  : [ 0.429372, 0.07 ]
  Cuv  : [ 4.097315, 0.06 ]
  Duv  : [ 17.363177, 7.0 ]
  Euv  : [ 0.0, 0.0 ]
  Adv  :  DEPENDENT
  Bdv  : [ 1.021082, 0.09 ]
  Cdv  : [ 4.863878, 0.41 ]
  Aubar: [ 0.0, 0.0 ] # not used (Aubar=Adbar)
  Bubar: [ 0.0, 0.0  ] # not used (Bubar=Bdbar)
  Cubar: [ 15.641426, 0.72 ]
  Dubar: [ 41.022109, 4.7 ]
  Adbar: [ 0.10017, 0.01 ]
  Bdbar: [ -0.172582, 0.007  ]
  Cdbar: [ 7.539023, 2.4 ]
  ZERO : [ 0.0, 0.0 ]          # zero
  fs : [ 0.4, 0.0 ]
  alphas : [ 0.113539, 0.0016 ]
  mtFit : [ 170.506070, 0.7 ]
  m1Value : [ 167.5, 0.0 ]
  m2Value : [ 170.0, 0.0 ]
  m3Value : [ 172.5, 0.0 ]
  m4Value : [ 175.0, 0.0 ]
  m5Value : [ 177.5, 0.0 ]

Parameterisations:
  par_uv:
    class: HERAPDF
    parameters: [Auv,Buv,Cuv,Duv,Euv]
  par_dv:
    class: HERAPDF
    parameters: [Adv,Bdv,Cdv]
  par_ubar:
    class: HERAPDF
    parameters: [Adbar,Bdbar,Cubar,Dubar]
  par_dbar:
    class: HERAPDF
    parameters: [Adbar,Bdbar,Cdbar]
  par_s:
    class: Expression
    expression: "Adbar*fs/(1-fs)*(x^Bdbar*(1-x)^Cdbar)"
  par_g:
    class: NegativeGluon
    parameters: [Ag,Bg,Cg,ZERO,Eg,Agp,Bgp,Cgp]

DefaultDecomposition: proton
Decompositions:
  proton:
    class: UvDvUbarDbarS
    xuv: par_uv
    xdv: par_dv
    xubar: par_ubar
    xdbar: par_dbar
    xs: par_s
    xg: par_g

DefaultEvolution: proton-QCDNUM

Evolutions:
  proton-QCDNUM:
    ? !include evolutions/QCDNUM.yaml
    decomposition: proton #this could be omitted, as the default decomposition is set
    # The following allows QCDNUM to read PDFs from other evolutions:
    # EvolutionCopy: "proton-LHAPDF"

Q0 : 1.378404875209 # Initial scale =sqrt(1.9)

? !include constants.yaml

byReaction:
  RT_DISNC:
    ? !include reactions/RT_DISNC.yaml
  APPLgrid:
    ? !include reactions/APPLgrid.yaml

# Specify HF scheme used for DIS NC processes:
hf_scheme_DISNC :
  defaultValue : 'RT_DISNC'        # global specification

# Specify HF scheme used for DIS CC processes:
hf_scheme_DISCC :
  defaultValue : 'BaseDISCC'       # global specification
