Minimizer: MINUIT
MINUIT:
  Commands: |
    set str 2
    #call fcn 3
    #migrad 20000
    #hesse
    call fcn 3

Parameters:
  Ag   :  DEPENDENT
  Bg   : [ -0.014834, 0.27  ]
  Cg   : [  9.106839, 0.32  ]
  Agp  : [  1.045190, 0.01  ]  # negative gluon
  Bgp  : [ -0.166400, 0.01  ]
  Cgp  : [ 25.0,      0.    ]  # fix C of negative gluon
  Auv  :  DEPENDENT
  Buv  : [  0.713453, 0.016 ]
  Cuv  : [  4.840721, 0.06  ]
  Euv  : [ 13.405266, 0.8   ]
  Adv  :  DEPENDENT
  Bdv  : [  0.805766, 0.06  ]
  Cdv  : [  4.079602, 0.3   ]
  CUbar: [  8.055252, 0.8   ]
  DUbar: [ 11.900269, 1.0   ]
  ADbar: [  0.175617, 0.01  ]
  BDbar: [ -0.172358, 0.004 ]
  CDbar: # another example of providing value, step etc.
    value: 4.885482
    step: 1.2345
  ZERO : [ 0. ]          # zero
  fs   : [ 0.4, 0.0 ]
  fd   : "=1-fs"
  AUbar: "=(1-fs)*ADbar"

Parameterisations:
  par_uv:
    class: HERAPDF
    parameters: [Auv,Buv,Cuv,ZERO,Euv]
  par_dv:
    class: HERAPDF
    parameters: [Adv,Bdv,Cdv]
  par_Ubar: # = ubar
    class: HERAPDF
    parameters: [AUbar,BDbar,CUbar,DUbar]
  par_Dbar: # = dbar + sbar
    class: HERAPDF
    parameters: [ADbar,BDbar,CDbar]
  par_dbar: # = (1-fs) Dbar
    class: Factor
    input: par_Dbar
    factor: fd
  par_s: # = sbar = fs Dbar
    class: Factor
    input: par_Dbar
    factor: fs
  par_g:
    class: NegativeGluon
    parameters: [Ag,Bg,Cg,ZERO,ZERO,Agp,Bgp,Cgp]

DefaultDecomposition: proton
Decompositions:
  proton:
    class: UvDvUbarDbarS
    # Note that HERAPDF parameterises Ubar and Dbar,
    # but this decomposition uses ubar and dbar
    xuv: par_uv
    xdv: par_dv
    xubar: par_Ubar
    xdbar: par_dbar
    xs: par_s
    xg: par_g

DefaultEvolution: proton-QCDNUM

Evolutions:
  proton-QCDNUM:
    ? !include evolutions/QCDNUM.yaml
    decomposition: proton #this could be omitted, as the default decomposition is set

# QCD parameters
Order: NLO
NFlavour: 5
isFFNS: 0
Q0 : 1.378404875209 # Initial scale =sqrt(1.9)
alphas : 0.118

? !include constants.yaml



byReaction:
  # RT DIS scheme settings:
  RT_DISNC:
    ? !include reactions/RT_DISNC.yaml

# Specify HF scheme used for DIS NC processes:
hf_scheme_DISNC :
  defaultValue : 'RT_DISNC'        # global specification

# Specify HF scheme used for DIS CC processes:
hf_scheme_DISCC :
  defaultValue : 'BaseDISCC'       # global specification

WriteLHAPDF6:
  name: "proton"
  description: "..."
  authors: "..."
  reference: "..."
    # use DefaultEvolution
  #evolution: proton-QCDNUM
    # take internal grid
  preferInternalGrid:
    # or define grid
  #Xrange: [1e-4, 1]
  #Qrange: [1,1000]
  #Xnpoints: 200
  #Qnpoints: 120
