Minimizer: MINUIT
MINUIT:
  Commands: |
    set str 2
    call fcn 3

Parameters:
  Ag   :  DEPENDENT
  Bg   : [ -0.014834, 0.27 ]
  Cg   : [  9.106839,  0.32 ]
  Agp  : [ 0.240458, 0.01 ]  # negative gluon
  Bgp  : [ -0.166400, 0.01 ]
  Cgp  : [ 25.0, 0.]  # fix C of negative gluon
  Auv  :  DEPENDENT
  Buv  : [ 0.713453, 0.016 ]
  Cuv  : [ 4.840721, 0.06 ]
  Duv  : [    0     ]
  Euv  : [ 13.405266, 0.8 ]
  Adv  :  DEPENDENT
  Bdv  : [ 0.805766, 0.06 ]
  Cdv  : [ 4.079602, 0.3 ]
  Aubar: [ 0.0, 0.0 ] # not used (Aubar=Adbar)
  Bubar: [ 0.0, 0.0  ] # not used (Bubar=Bdbar)
  Cubar: [ 8.055252, 0.8 ]
  Dubar: [ 11.900269, 1.0 ]
  Adbar: [ 0.10537, 0.01 ]
  Bdbar: [ -0.172358, 0.004  ]
  Cdbar: # another example of providing value, step etc.
    value: 4.885482
    step: 1.2345
  ZERO : [ 0. ]          # zero
  fs : [ 0.4, 0.0 ]

Parameterisations:
  par_uv:
    class: HERAPDF
    parameters: [Auv,Buv,Cuv,Duv,Euv]
  par_dv:
    class: HERAPDF
    parameters: [Adv,Bdv,Cdv]
  par_ubar:
    class: HERAPDF
    parameters: [Adbar,Bdbar,Cubar,Dubar]
  par_dbar:
    class: HERAPDF
    parameters: [Adbar,Bdbar,Cdbar]
  par_s:
    #class: HERAPDF
    #parameters: [As,Bs,Cs]
    # parametrise as expression: otherwise how to parametrise it as fs/(1-fs)*par_dbar using HERAPDF?
    class: Expression
    expression: "Adbar*fs/(1-fs)*(x^Bdbar*(1-x)^Cdbar)"
  par_g:
    class: NegativeGluon
    parameters: [Ag,Bg,Cg,ZERO,ZERO,Agp,Bgp,Cgp]

DefaultDecomposition: proton
Decompositions:
  proton:
    class: UvDvUbarDbarS
    xuv: par_uv
    xdv: par_dv
    xubar: par_ubar
    xdbar: par_dbar
    xs: par_s
    xg: par_g

DefaultEvolution: proton-QCDNUM

Evolutions:
  proton-QCDNUM:
    ? !include evolutions/QCDNUM.yaml
    decomposition: proton #this could be omitted, as the default decomposition is set

# QCD parameters
Order: NLO
NFlavour: 5
isFFNS: 0
Q0 : 1.378404875209 # Initial scale =sqrt(1.9)
alphas : 0.118

? !include constants.yaml



byReaction:
  # RT DIS scheme settings:
  RT_DISNC:
    ? !include reactions/RT_DISNC.yaml

# Specify HF scheme used for DIS NC processes:
hf_scheme_DISNC :
  defaultValue : 'RT_DISNC'        # global specification

# Specify HF scheme used for DIS CC processes:
hf_scheme_DISCC :
  defaultValue : 'BaseDISCC'       # global specification

WriteLHAPDF6:
  name: "proton"
  description: "..."
  authors: "..."
  reference: "..."
    # use DefaultEvolution
  #evolution: proton-QCDNUM
    # take internal grid
  preferInternalGrid:
    # or define grid
  #Xrange: [1e-4, 1]
  #Qrange: [1,1000]
  #Xnpoints: 200
  #Qnpoints: 120
