C
C Basic definitions for 
C

      integer NTOT            !> Total number of data points
      parameter(NTOT = 1500)

      integer nset            !> Total number of datasets   
      parameter (NSET = 120)

      integer NKFactMax          !> Max. number of k-factors
      parameter (NKFactMax = 10)
      
      integer NBinDimensionMax   !> MAx. number of abstract bins
      parameter (NBinDimensionMax=10)      


      