      double precision
     & THEO(NTOT),
C-1- 09/08/2010: added arrays =====================
     & THEO_DGLAP(NTOT),
     & THEO_DIPOLE(NTOT),
     & DIPOLE_F2(NTOT),
     & DIPOLE_FL(NTOT),
C-2- 09/08/2010: end of the addition ==============
     & f2sh(NTOT),flsh(NTOT), xf3sh(NTOT)
      
      common/c_theo/theo,
     & theo_dglap,
     & theo_dipole,
     & dipole_f2,
     & dipole_fl,
     & f2sh,flsh,xf3sh
