#!/bin/bash
#####################################################################
## Configuration ####################################################

## Programs versions
lhapdfver=6.5.4
hathorver=2.0
hoppetver=1.2.0
applgridver=1.6.32
qcdnumver=18-00-00
apfelver=3.0.6
apfelgridver=1.0.5
apfelxxver=4.0.0
dyturbover=1.2

# skip some packages depending on xfitter version
skip_apfelgrid=0
skip_dyturbo=1

## Optional manual configurations
#MANUALCONF=1

## Option 1: Use local environment
## These settings assume that root is already in your PATH and boost lib is installed
## For versions older than 1.1.0, need to specify the location of CERNLIB
#MODE=local
#export CERN_ROOT=/usr/lib

## Option 2: Setup environment from CERN cvmfs
## These settings include compiler, cernlib and root
#MODE=cern
#gccv=4.6
#os=slc6
#arch=x86_64
#rootversion=5.34.18

## End of Configuration ####################################################
#####################################################################
#Check for dummies
if [[ $0 == bash || $0 = csh ]]
then
    echo "Please don't source me, I am an executable!"
    echo "Give me attributes with:"
    echo "chmod +x install-xfitter"
    echo "and run me with:"
    echo "./install-xfitter"
    return 2
fi

if [[ -z $1 ]]
then
    echo
    echo "usage:"
    echo "$0 <version|deps>"
    echo
    echo "available versions:"
    vers=`git ls-remote --tags https://gitlab.cern.ch/fitters/xfitter.git | sed 's|/| |g; s|\^| |' | awk '{print $4}' | uniq`
    echo "$vers"
    echo "master"
    echo
    echo "to reinstall only dependences, run:"
    echo "$0 deps"
    echo
    exit
fi
mode=$1
shift 1

#in deps mode, read version from the version file
if [[ $mode != "deps" ]]
    then
    version=$mode
else
    if [[ ! -e version ]]
        then
        # assume it is master (e.g. for gitlab CI)
        version="master"
        #
        #echo
        #echo "could not find file \"version\""
        #echo "cannot determine current version"
        #echo "run first:"
        #echo "$0 <version>"
        #echo
        #exit
    else
        version=`cat version`
    fi
    echo "reinstalling dependencies for xFitter version $version"
fi
# strip the xfitter version
stripversion=`echo $version |sed "s/\.//g"`


#check that requested version exists
if [[ $version == "2.0.0" ]] || [[ $version == "2.0.1" ]]
    then
    # use older QCDNUM for xfitter-2.0.0
    if [[ $version == "2.0.0" ]]; then
      qcdnumver=17-01-13
    fi
    exist=0
    for ver in ``
    do
        if [[ $version == $ver ]]
        then
            exist=1
        fi
    done

    vers=`git ls-remote --tags https://gitlab.cern.ch/fitters/xfitter.git | sed 's|/| |g; s|\^| |' | awk '{print $4}' | uniq`

    for ver in $vers
    do
        if [[ $version == $ver ]]
        then
            exist=1
        fi
    done

    if [[ $exist == 0 ]]
    then
        echo
        echo "version $version not found, available versions:"
        echo ""
        echo "$vers"
        echo "master"
        echo
        exit
    fi
fi

if [[ $mode != "deps" && -e xfitter-${version} ]]
then
    echo
    echo "xfitter-${version} already exists, remove it first"
    echo "To reinstall only dependences, run:"
    echo "$0 deps"
    echo
    exit
fi

#automatically detect system:
if [[ -z $MANUALCONF ]]
then
    which sw_vers >& /dev/null
    if [[ $? == 0 ]]
    then
        echo "Detected Mac OS X system"
        MODE=local
    else
        SYS=$(echo `lsb_release -i |cut -d: -f2`)
        ver=$(echo `lsb_release -r |cut -d: -f2`)
        if [[ $SYS == Scientific* && $ver == 6.* ]]
        then
            echo "Detected SL6 Linux distribution"
            MODE=cern
            gccv=4.9
	        cmakev=3.20.0
            echo "Using gcc version = ${gccv}"
            os=slc6
            arch=x86_64
            rootversion=5.34.36
            boostver=1.53.0
            pyth=2.7
        elif [[ $SYS == CentOS* && $ver == 7.* ]]
        then
            echo "Detected CentOS7 Linux distribution"
            MODE=cern
            gccv=4.9
	        cmakev=3.20.0
            os=centos7
            arch=x86_64
            rootversion=6.06.08
            boostver=1.53.0
            pyth=2.7
        elif [[ $SYS == "Ubuntu" ]]
        then
            echo "Detected Ubuntu distribution"
            MODE=local
        elif [[ -e /cvmfs/sft.cern.ch ]]
	then
            echo "System not recognized, but cvmfs is mounted"
            MODE=cvmfs
	    #gccv=10.3.0
	    #arch=x86_64
	    #os=centos7
	    #cmakev=3.20.0
	    #rootversion=6.06.08
	    #boostver=1.53.0
	    #pyth=2.7

	    #. /cvmfs/sft.cern.ch/lcg/releases/gcc/10.3.0-f5826/x86_64-centos7/setup.sh
	    #. /cvmfs/sft.cern.ch/lcg/releases/ROOT/6.24.06-3455f/x86_64-centos7-gcc10-opt/bin/thisroot.sh
            #echo "Using gcc version = 10.3.0"

	    #setup entire view (fails on cmake for ceres)
	    #. /cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-centos7-gcc10-opt/setup.sh

	    #setup older gcc
	    . /cvmfs/sft.cern.ch/lcg/contrib/gcc/4.9.3/x86_64-cc7-gcc49-opt/setup.sh
	    #. /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.06.08/x86_64-centos7-gcc49-opt/root/bin/thisroot.sh
            echo "Using gcc version = 4.9.3"
        else
            echo "Sorry, I don't recognize your system:"
            echo "$SYS $ver"
            echo "I will assume you have root installed in your system,"
            echo "gcc version >= 4.3, python, boost libraries, and wget"
            echo "If this doesn't work, and you have /cvmfs/sft.cern.ch mounted"
            echo "edit me (I am $0) and try to setup appropriate settings"
            echo "in the section: manual configuration"
            echo
            MODE="local"
        fi
    fi
fi
if [[ $MODE == "cern" ]]
    then
    if [[ ! -e /cvmfs/sft.cern.ch ]]
        then
        echo
        echo "/cvmfs/sft.cern.ch not mounted, forcing local MODE"
        echo "Fasten you seat belt"
        echo "I hope you have root, gcc >= 4.8, python and boost libraries"
        echo "all installed in your system"
        echo
        MODE="local"
    fi
fi

if [[ $MODE == "cern" ]]
then
    compiler=`echo gcc${gccv} | sed "s/\.//"`
    . /cvmfs/sft.cern.ch/lcg/contrib/gcc/${gccv}/${arch}-${os}/setup.sh
    . /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/${rootversion}/${arch}-${os}-${compiler}-opt/root/bin/thisroot.sh
    PATH=/cvmfs/sft.cern.ch/lcg/contrib/CMake/${cmakev}/Linux-x86_64/bin/:${PATH}
    if [[ $os == slc6 ]]
    then
        export BOOST=--with-boost=/cvmfs/sft.cern.ch/lcg/external/Boost/${boostver}_python${pyth}/${arch}-${os}-${compiler}-opt
    fi
fi

#check some basic dependendencies before starting the installation
which git >& /dev/null
if [[ $? != 0 ]]
then
    echo "Error, git not found"
    exit
fi

which root >& /dev/null
if [[ $? != 0 ]]
then
    echo "Error, root not found"
    exit
fi

# Get root c flags:
root_c_flags=`root-config --cflags`
echo "Compiling with c++ flags " 
echo ${root_c_flags}

which wget >& /dev/null
if [[ $? == 0 ]]
then
    http=wget
else
    which curl >& /dev/null
    if [[ $? == 0 ]]
    then
        http=curl
    else
        echo "Error, wget or curl not found"
        exit
    fi
fi

#directory:
CURRENTDIR=`pwd`

#clean up
rm version setup.sh compile quickstart.readme.txt >& /dev/null
rm install.log >& /dev/null



# keep for debugging
installDeps=1


if [[ $installDeps == 0 ]]
then
   echo "Skip installation of dependences"
else
#Make all dependencies
    rm -rf deps >& /dev/null
    mkdir deps
    cd deps
#lhapdf:
    echo "Installing LHAPDF $lhapdfver..."
    if (( `echo $lhapdfver |cut -d. -f1` >= 6 ))
    then
        lhapdf="LHAPDF"
        withboost=$BOOST
    else
        lhapdf="lhapdf"
    fi

    if [[ $http == "curl" ]]
    then
        curl https://lhapdf.hepforge.org/downloads/${lhapdf}-${lhapdfver}.tar.gz > ${lhapdf}-${lhapdfver}.tar.gz 2>> $CURRENTDIR/install.log
    else
        wget --no-check-certificate https://lhapdf.hepforge.org/downloads/${lhapdf}-${lhapdfver}.tar.gz >> $CURRENTDIR/install.log 2>&1
    fi
    cat $CURRENTDIR/install.log
    tar xfz ${lhapdf}-${lhapdfver}.tar.gz  >> $CURRENTDIR/install.log 2>&1
    cat $CURRENTDIR/install.log 
    cd ${lhapdf}-${lhapdfver}
    ./configure --prefix=$CURRENTDIR/deps/lhapdf --disable-python  >> $CURRENTDIR/install.log  2>&1
    if [[ $? != 0 ]]
    then
        echo "Error, check install.log for details"
        exit
    fi
    make -j 8 install >> $CURRENTDIR/install.log  2>&1
    if [[ $? != 0 ]]
    then
        echo "Error, check install.log for details"
        exit
    fi
    cd - >& /dev/null

#Hathor:
    echo "Installing Hathor $hathorver..."
    hathor="Hathor"
    if [[ $http == "curl" ]]
    then
        curl https://www.physik.hu-berlin.de/de/pep/tools/Hathor-${hathorver}.tar.gz 2>> $CURRENTDIR/install.log
    else
        wget --no-check-certificate https://www.physik.hu-berlin.de/de/pep/tools/Hathor-${hathorver}.tar.gz >> $CURRENTDIR/install.log 2>&1
    fi
    tar xfz Hathor-${hathorver}.tar.gz  >> $CURRENTDIR/install.log 2>&1
    cd Hathor-${hathorver}/lib
    # need to provide LHAPDF directory and add -fPIC flag to CFLAGS and FFLAGS
    make LHAPDF=$CURRENTDIR/deps/lhapdf V=1 CFLAGS="${root_c_flags} -O2 -Wall -fPIC" FFLAGS='-ffixed-line-length-132 -fPIC -std=legacy' -j 8 >> $CURRENTDIR/install.log  2>&1 
    if [[ $? != 0 ]]
    then
        echo "Error, check install.log for details"
        exit
    fi
    cd - >& /dev/null

 #hoppet:
    echo "Installing HOPPET $hoppetver..."
    if [[ $http == "curl" ]]
    then
        curl http://hoppet.hepforge.org/downloads/hoppet-${hoppetver}.tgz > hoppet-${hoppetver}.tgz 2>> $CURRENTDIR/install.log
    else
        wget --no-check-certificate http://hoppet.hepforge.org/downloads/hoppet-${hoppetver}.tgz >> $CURRENTDIR/install.log 2>&1
    fi
    tar xfz hoppet-${hoppetver}.tgz  >> $CURRENTDIR/install.log  2>&1
    cd hoppet-${hoppetver}
    ./configure --prefix=$CURRENTDIR/deps/hoppet  >> $CURRENTDIR/install.log  2>&1
    if [[ $? != 0 ]]
    then
        echo "Error, check install.log for details"
        exit
    fi
    make -j 8 install  >> $CURRENTDIR/install.log  2>&1
    if [[ $? != 0 ]]
    then
        echo "Error, check install.log for details"
#       exit
    fi
    cd - >& /dev/null

 # setup paths for applgrid:
    export PATH=$CURRENTDIR/deps/hoppet/bin/:$PATH
    export PATH=$CURRENTDIR/deps/lhapdf/bin/:$PATH
    export HATHOR_DIR=$CURRENTDIR/deps/Hathor-${hathorver}
    export LD_LIBRARY_PATH=$CURRENTDIR/deps/lhapdf/lib/:$LD_LIBRARY_PATH
    echo `lhapdf-config --prefix`/lib*/python*/site-packages > /tmp/xf_py1234_a
    export PYTHONPATH=$PYTHONPATH:`cat /tmp/xf_py1234_a`
    rm /tmp/xf_py1234_a

 #applgrid:
    echo "Installing APPLGRID $applgridver..."
    APPLGRID_URL=https://applgrid.hepforge.org/downloads/applgrid-"$applgridver".tgz
    if [[ $http == "curl" ]]
    then
        curl $APPLGRID_URL > applgrid-$applgridver.tgz  2>> $CURRENTDIR/install.log
    else
        wget --no-check-certificate $APPLGRID_URL >> $CURRENTDIR/install.log 2>&1
    fi
    tar xfz applgrid-$applgridver.tgz  >> $CURRENTDIR/install.log  2>&1
    cd applgrid-$applgridver
    # need to supply c++1X flag from root explicitly
    ./configure CXXFLAGS="${root_c_flags}" --prefix=$CURRENTDIR/deps/applgrid  >> $CURRENTDIR/install.log  2>&1
    if [[ $? != 0 ]]
    then
        echo "Error, check install.log for details"
        exit
    fi
    make -j 8  >> $CURRENTDIR/install.log  2>&1
    if [[ $? != 0 ]]
    then
        echo "Error, check install.log for details"
        exit
    fi
    make -j 8 install  >> $CURRENTDIR/install.log  2>&1
    if [[ $? != 0 ]]
    then
        echo "Error, check install.log for details"
        exit
    fi
    cd - >& /dev/null

    export PATH=$CURRENTDIR/deps/applgrid/bin/:$PATH

 #apfel
    echo "Installing APFEL $apfelver..."
    if [[ $http == "curl" ]]
    then
        curl https://github.com/scarrazza/apfel/archive/${apfelver}.tar.gz > ${apfelver}.tar.gz 2 >> $CURRENTDIR/install.log
    else
        wget --no-check-certificate https://github.com/scarrazza/apfel/archive/${apfelver}.tar.gz >> $CURRENTDIR/install.log 2>&1
    fi
    mv ${apfelver}.tar.gz apfel-${apfelver}.tar.gz
    tar xfvz apfel-${apfelver}.tar.gz >> $CURRENTDIR/install.log 2>&1
    cd apfel-${apfelver}
    ./configure --prefix=$CURRENTDIR/deps/apfel --disable-lhapdf >> $CURRENTDIR/install.log  2>&1

    if [[ $? != 0 ]]
    then
        echo "Error, check install.log for details"
        exit
    fi
    make -j 8 install  >> $CURRENTDIR/install.log  2>&1
    if [[ $? != 0 ]]
    then
        echo "Error, check install.log for details"
        exit
    fi
    cd - >& /dev/null
 # setup paths for apfel:
    export PATH=$CURRENTDIR/deps/apfel/bin/:$PATH

#Importing tables for Small-x resummation studies
    echo "Installing HELL tables..."
    if [[ $http == "curl" ]]
    then
      curl https://www.ge.infn.it/~bonvini/hell/downloads/HELLx.v3.0.tgz > HELLx.v3.0.tgz 2 >> $CURRENTDIR/install.log
      curl https://www.ge.infn.it/~bonvini/hell/downloads/HELLx-data.v3.tgz > HELLx-data.v3.tgz 2 >> $CURRENTDIR/install.log
    else
      wget --no-check-certificate https://www.ge.infn.it/~bonvini/hell/downloads/HELLx.v3.0.tgz >> $CURRENTDIR/install.log  2>&1
      wget --no-check-certificate https://www.ge.infn.it/~bonvini/hell/downloads/HELLx-data.v3.tgz >> $CURRENTDIR/install.log  2>&1
    fi

    tar xzf HELLx.v3.0.tgz >> $CURRENTDIR/install.log  2>&1
    tar xzf HELLx-data.v3.tgz >> $CURRENTDIR/install.log  2>&1

    cp -r HELLx/data/* $CURRENTDIR/deps/apfel/share/apfel/.

 #apfelgrid
    if [[ $skip_apfelgrid != 1 ]]; then
        wget --no-check-certificate http://www.hepforge.org/archive/lhapdf/pdfsets/6.2/NNPDF30_nlo_as_0118.tar.gz  >> $CURRENTDIR/install.log  2>&1
        tar xvzpf NNPDF30_nlo_as_0118.tar.gz >> $CURRENTDIR/install.log  2>&1
        mv NNPDF30_nlo_as_0118 lhapdf/share/LHAPDF >> $CURRENTDIR/install.log  2>&1
        rm NNPDF30_nlo_as_0118.tar.gz  >> $CURRENTDIR/install.log  2>&1
        echo "Installing APFELgrid $apfelgridver..."
      # tmp solution is to use fork @zenaiev
	if [[ $http == "curl" ]]
	then
            curl https://github.com/zenaiev/APFELgrid/archive/v${apfelgridver}.tar.gz > v${apfelgridver}.tar.gz 2 >> $CURRENTDIR/install.log
	else
            wget --no-check-certificate https://github.com/zenaiev/APFELgrid/archive/v${apfelgridver}.tar.gz >> $CURRENTDIR/install.log 2>&1
	fi
	mv v${apfelgridver}.tar.gz APFELgrid-${apfelgridver}.tar.gz
	tar xfvz APFELgrid-${apfelgridver}.tar.gz >> $CURRENTDIR/install.log 2>&1
	cd APFELgrid-${apfelgridver}
	sed -i 's|wget|wget --no-check-certificate|' setup.sh
	./setup.sh  >> $CURRENTDIR/install.log  2>&1
	if [[ $? != 1 ]]
	then
            echo "Error, check install.log for details"
	fi
	make -j 8 install
	cd - >& /dev/null
    fi
    
 #apfel
    echo "Installing APFELxx $apfelxxver..."
    if [[ $http == "curl" ]]
    then
        curl https://github.com/vbertone/apfelxx/archive/v${apfelxxver}.tar.gz > v${apfelxxver}.tar.gz 2 >> $CURRENTDIR/install.log
    else
        wget --no-check-certificate https://github.com/vbertone/apfelxx/archive/v${apfelxxver}.tar.gz  >> $CURRENTDIR/install.log 2>&1
    fi
    mv v${apfelxxver}.tar.gz apfelxx-${apfelxxver}.tar.gz
    tar xfvz apfelxx-${apfelxxver}.tar.gz >> $CURRENTDIR/install.log 2>&1

    cd apfelxx-${apfelxxver}
    cmake3 -DCMAKE_INSTALL_PREFIX=$CURRENTDIR/deps/apfelxx >> $CURRENTDIR/install.log  2>&1
    make -j 8 >> $CURRENTDIR/install.log  2>&1
    make -j 8 install >> $CURRENTDIR/install.log  2>&1
    
    export PATH=$CURRENTDIR/deps/apfelxx/bin/:$PATH
    cd - >& /dev/null
 #qcdnum
    echo "Installing QCDNUM $qcdnumver..."
    qcdnumstripver=`echo $qcdnumver |sed "s/-//g"`
    if [[ $http == "curl" ]]
    then 
        curl https://www.nikhef.nl/~h24/qcdnum-files/download/qcdnum${qcdnumstripver}.tar.gz > qcdnum${qcdnumstripver}.tar.gz 2>> $CURRENTDIR/install.log
    else
        wget https://www.nikhef.nl/~h24/qcdnum-files/download/qcdnum${qcdnumstripver}.tar.gz >> $CURRENTDIR/install.log 2>&1
    fi
    tar xfz qcdnum${qcdnumstripver}.tar.gz  >> $CURRENTDIR/install.log  2>&1
    cd qcdnum-${qcdnumver}

    ./configure --prefix=$CURRENTDIR/deps/qcdnum  >> $CURRENTDIR/install.log  2>&1
    export PATH=$CURRENTDIR/deps/qcdnum/bin/:$PATH

    if [[ $? != 0 ]]
    then
        echo "Error, check install.log for details"
        exit
    fi
    make -j 8 install  >> $CURRENTDIR/install.log  2>&1
    if [[ $? != 0 ]]
    then
        echo "Error, check install.log for details"
        exit
    fi
    cd - >& /dev/null

 #dyturbo
    if [[ $skip_dyturbo != 1 ]]; then
        echo "Installing DYTurbo ${dyturbover}..."
        if [[ $http == "curl" ]]
        then
	    curl https://dyturbo.hepforge.org/downloads/dyturbo-${dyturbover}.tar.gz > dyturbo-${dyturbover}.tar.gz 2>> $CURRENTDIR/install.log
        else
	    wget --no-check-certificate https://dyturbo.hepforge.org/downloads/dyturbo-${dyturbover}.tar.gz >> $CURRENTDIR/install.log 2>&1
        fi
        tar xfz dyturbo-${dyturbover}.tar.gz  >> $CURRENTDIR/install.log  2>&1
        cd dyturbo-${dyturbover}

        export CXXFLAGS="${CXXFLAGS} -std=c++0x"
        ./configure --enable-Ofast --disable-tlsopt >> $CURRENTDIR/install.log  2>&1 --enable-Ofast  >> $CURRENTDIR/install.log  2>&1
        export PATH=$CURRENTDIR/deps/dyturbo-${dyturbover}/bin/:$PATH

        if [[ $? != 0 ]]
        then
            echo "Error, check install.log for details"
            exit
        fi
        make -j 8 install  >> $CURRENTDIR/install.log  2>&1
        if [[ $? != 0 ]]
        then
            echo "Error, check install.log for details"
            exit
        fi
        cd - >& /dev/null
    fi
    
  # numdiff
    numdiff -v >& /dev/null
    if [[ `echo $?` != "0" ]]; then
      numdiffver='5.9.0'
      echo "Installing numdiff $numdiffver..."
      numdiff_url=http://nongnu.askapache.com/numdiff/numdiff-${numdiffver}.tar.gz
      if [[ $http == "curl" ]]
      then
          curl ${numdiff_url} > qcdnum${qcdnumstripver}.tar.gz 2>> $CURRENTDIR/install.log
      else
          wget --no-check-certificate ${numdiff_url} >> $CURRENTDIR/install.log 2>&1
      fi
      tar xfz numdiff-${numdiffver}.tar.gz  >> $CURRENTDIR/install.log  2>&1
      cd numdiff-${numdiffver}
      ./configure  --prefix=$CURRENTDIR/deps/numdiff  >> $CURRENTDIR/install.log  2>&1
      echo export PATH=$CURRENTDIR/deps/numdiff/bin/:\$PATH >> $CURRENTDIR/setup.sh
      if [[ $? != 0 ]]
      then
          echo "Error, check install.log for details"
          exit
      fi
      make -j 8 install  >> $CURRENTDIR/install.log  2>&1
      if [[ $? != 0 ]]
      then
          echo "Error, check install.log for details"
          exit
      fi
      cd - >& /dev/null
    fi
fi
cd $CURRENTDIR

 #xfitter
if [[ $mode != "deps" ]]
then
    echo "Installing xFitter $version..."


    if [[ $version == "master" ]]
    then
        git clone https://gitlab.cern.ch/fitters/xfitter.git >> $CURRENTDIR/install.log  2>&1
        mv xfitter xfitter-master
    else
        if [[ $http == "curl" ]]
        then
            curl 'https://www.xfitter.org/xFitter/xFitter/DownloadPage?action=AttachFile&do=get&target=xfitter-'$version'.tgz' > xfitter-$version.tar.gz
        else
            wget 'https://www.xfitter.org/xFitter/xFitter/DownloadPage?action=AttachFile&do=get&target=xfitter-'$version'.tgz' -O xfitter-$version.tar.gz  >> $CURRENTDIR/install.log 2>&1
        fi
       # unpack nicely:
        rm -fr xfitter-${version}
        mkdir xfitter-${version} ; tar xfz xfitter-${version}.tar.gz -C xfitter-${version} --strip-components 1
    fi
#else
#    make -C xfitter-${version} clean >> $CURRENTDIR/install.log  2>&1
fi


#make a setup run enviroment script
echo $version > version
echo "export CURRENTDIR=`pwd`" >> setup.sh
echo "export version=\`cat version\`" >> setup.sh
echo "export PATH=$CURRENTDIR/xfitter-$version/bin:\$PATH" >> setup.sh
echo "export PATH=$CURRENTDIR/deps/hoppet/bin:\$PATH" >> setup.sh
echo "export PATH=$CURRENTDIR/deps/applgrid/bin:\$PATH" >> setup.sh
echo "export PATH=$CURRENTDIR/deps/lhapdf/bin:\$PATH" >> setup.sh
echo "export PATH=$CURRENTDIR/deps/apfel/bin:\$PATH" >> setup.sh
echo "export PATH=$CURRENTDIR/deps/mela/bin:\$PATH" >> setup.sh
echo "export PATH=$CURRENTDIR/deps/apfelxx/bin:\$PATH" >> setup.sh
echo "export PATH=$CURRENTDIR/deps/dyturbo-${dyturbover}/bin:\$PATH" >> setup.sh

echo `lhapdf-config --prefix`/lib*/python*/site-packages > /tmp/xf_py1234_a
echo "export PYTHONPATH=$PYTHONPATH:`cat /tmp/xf_py1234_a` " >> setup.sh
rm /tmp/xf_py1234_a

echo export LD_LIBRARY_PATH=\$CURRENTDIR/deps/hoppet/lib/:\$LD_LIBRARY_PATH   >> setup.sh
echo export LD_LIBRARY_PATH=\$CURRENTDIR/deps/lhapdf/lib/:\$LD_LIBRARY_PATH   >> setup.sh
echo export HATHOR_DIR=$CURRENTDIR/deps/Hathor-${hathorver}       >> setup.sh
echo export LD_LIBRARY_PATH=\$CURRENTDIR/deps/applgrid/lib/:\$LD_LIBRARY_PATH >> setup.sh
echo export LD_LIBRARY_PATH=\$CURRENTDIR/deps/apfel/lib/:\$LD_LIBRARY_PATH >> setup.sh
echo export LD_LIBRARY_PATH=\$CURRENTDIR/deps/mela/lib/:\$LD_LIBRARY_PATH >> setup.sh
echo export LD_LIBRARY_PATH=\$CURRENTDIR/deps/qcdnum/lib/:\$LD_LIBRARY_PATH >> setup.sh
echo export LD_LIBRARY_PATH=\$CURRENTDIR/deps/dyturbo-${dyturbover}/lib/:\$LD_LIBRARY_PATH >> setup.sh
echo "export PATH=$CURRENTDIR/deps/qcdnum/bin:\$PATH" >> setup.sh


if [[ $MODE == "cern" ]]
then
    echo . /cvmfs/sft.cern.ch/lcg/contrib/gcc/${gccv}/${arch}-${os}/setup.sh            >> setup.sh

    echo PATH=/cvmfs/sft.cern.ch/lcg/contrib/CMake/${cmakev}/Linux-x86_64/bin/:\$PATH >> setup.sh
    echo "cd /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/${rootversion}/${arch}-${os}-${compiler}-opt/root/" >> setup.sh
    echo ". /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/${rootversion}/${arch}-${os}-${compiler}-opt/root/bin/thisroot.sh ">> setup.sh
    echo "cd -" >>setup.sh
fi

if [[ $MODE == "cvmfs" ]]
then
    #echo . /cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-centos7-gcc10-opt/setup.sh >> setup.sh
    echo . /cvmfs/sft.cern.ch/lcg/contrib/gcc/4.9/x86_64-cc7/setup.sh  >> setup.sh
fi

#make a compilation script
echo source ./setup.sh > compile
echo export PATH=\$CURRENTDIR/deps/hoppet/bin/:\$PATH       >> compile
echo export PATH=\$CURRENTDIR/deps/lhapdf/bin/:\$PATH       >> compile
echo export HATHOR_DIR=$CURRENTDIR/deps/Hathor-${hathorver}       >> compile
echo export PATH=\$CURRENTDIR/deps/applgrid/bin/:\$PATH     >> compile
echo export PATH=\$CURRENTDIR/deps/apfel/bin/:\$PATH     >> compile
echo export PATH=\$CURRENTDIR/deps/mela/bin/:\$PATH     >> compile
echo export PATH=\$CURRENTDIR/deps/dyturbo-${dyturbover}/bin/:\$PATH     >> compile


if [[ $mode != "deps" ]]
then
  echo cd xfitter-\$version                                        >> compile
fi

# check for YAML
# xfitter 2.0.0 and 2.0.1 do not need YAML
if [[ $version != "2.0.0" ]] && [[ $version != "2.0.1" ]]; then
  HAVEYAML=0
  rm -f test-tmp.cc
  echo "#include <yaml.h>" >> test-tmp.cc
  echo "yaml_document_t doc;" >> test-tmp.cc
  g++ -c ${root_c_flags} $CPPFLAGS test-tmp.cc >& /dev/null
  if [ `echo $?` -eq 0 ]; then
    echo "YAML yes" >> $CURRENTDIR/install.log
    HAVEYAML=1
  else
    echo "YAML no" >> $CURRENTDIR/install.log
  fi
  HAVEYAMLCPP=0
  rm -f test-tmp.cc
  echo "#include <yaml-cpp/yaml.h>" >> test-tmp.cc
  echo "YAML::Node node;" >> test-tmp.cc
  g++ -c ${root_c_flags} $CPPFLAGS test-tmp.cc >& /dev/null
  if [ `echo $?` -eq 0 ]; then
    echo "YAMLCPP yes" >> $CURRENTDIR/install.log
    HAVEYAMLCPP=1
  else
    echo "YAMLCPP no" >> $CURRENTDIR/install.log
  fi
  rm -f test-tmp.cc
  rm -f test-tmp.o

  if [ $HAVEYAML -eq 0 ] || [ $HAVEYAMLCPP -eq 0 ]; then
    #echo "Installing YAML"
    xfitter-${version}/tools/install-yaml
    echo source $CURRENTDIR/setup_yaml.sh >> compile
    echo source $CURRENTDIR/setup_yaml.sh >> setup.sh
  fi
fi

chmod +x compile

# configure
if [[ $mode != "deps" ]]
then
  if [[ $version == "2.0.0" ]] || [[ $version == "2.0.1" ]]; then
    echo autoreconf --install                                 >> compile
    echo ./configure --enable-applgrid --enable-lhapdf --enable-apfel --enable-apfelxx --enable-mela  --enable-apfelgrid --enable-process    >> compile
    echo make -j 8 install                                    >> compile
  elif [[ $version == "master_before_PionCeres_merge" ]] || [[ $version == "test_ceres_v0.01" ]]; then
    # SZ 10.07.2019 apfelgrid produces linking error in PionCeres
    echo ./configure --enable-applgrid --enable-lhapdf --enable-hathor --enable-apfel --enable-apfelxx --enable-mela --enable-process    >> compile
    echo make -j 8 install                                    >> compile
    echo autoreconf --install                                 >> compile
  else
    # cmake compilation
    echo ./make.sh install >> compile
  fi
  echo "Compiling xFitter $version..."
fi

./compile >> $CURRENTDIR/install.log  2>&1
if [[ $? != 0 ]]
then
    echo "Error, check install.log for details"
    exit
fi

source ./setup.sh

if [[ $mode == "deps" ]]
then
  echo "Installing xfitter dependencies is complete"
  echo "Check install.log file for details"
else
  # run test
  cd xfitter-${version}
  bin/xfitter >> $CURRENTDIR/install.log  2>&1

  if [[ $? != 0 ]]
  then
      echo "Error in testing xfitter executable, check install.log for details"
      exit
  fi
  cd - >& /dev/null
  echo "xFitter installation successful!"
  echo "Check install.log file for details"
  echo
  # setup a run dir
  if [[ ! -e run ]]
  then
      mkdir -p run
      cp  xfitter-${version}/steering.txt \
          xfitter-${version}/parameters.yaml \
          xfitter-${version}/constants.yaml \
          run
      rsync -a --exclude=".*" xfitter-${version}/datafiles run/
  else
      echo "\"run\" directory already exists, I won't touch it"
      echo
  fi

  #quick start guide
  if [[ ! -e quickstart-readme.txt ]]
  then
      echo "for a quick start do:" >> quickstart-readme.txt
      echo >> quickstart-readme.txt
      echo "source setup.sh #setup environment" >> quickstart-readme.txt
      echo "cd run          #enter your run directory" >> quickstart-readme.txt
      echo "xfitter          #run your fit" >> quickstart-readme.txt
      echo >> quickstart-readme.txt
      echo "The fit options are controlled by the 3 files steering.txt, parameters.yaml, and constants.yaml" >> quickstart-readme.txt
      echo "Data and theory files are in datafiles directory" >> quickstart-readme.txt
      echo >> quickstart-readme.txt
      echo "After the fit, display you results with:" >> quickstart-readme.txt
      echo "xfitter-draw output/" >> quickstart-readme.txt
      echo "A file output/plots.pdf will be created" >> quickstart-readme.txt
      echo "You can find further documentation in xfitter-$version/README and xfitter-$version/doc/tex/manual/" >> quickstart-readme.txt
      echo "-----------------------------------------------------------"
      cat quickstart-readme.txt
      echo "-----------------------------------------------------------"
      echo
      echo "To read again these instructions, see quickstart-readme.txt"
      echo "Have fun!"
  fi
fi
