#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Program version
qcdnumver=18-00-00

#Check for dummies
if [[ $0 == bash || $0 = csh ]]
then
    echo "Please don't source me, I am an executable!"
    echo "Give me attributes with:"
    echo "chmod +x install-xfitter"
    echo "and run me with:"
    echo "./install-xfitter"
    return 2
fi

which wget >& /dev/null
if [[ $? == 0 ]]
then
    http=wget
else
    which curl >& /dev/null
    if [[ $? == 0 ]]
    then
        http=curl
    else
        echo "Error, wget or curl not found"
        exit
    fi
fi

#directory:
CURRENTDIR=`pwd`

mkdir -p deps
cd deps

#qcdnum
echo "Installing QCDNUM $qcdnumver..."
qcdnumstripver=`echo $qcdnumver |sed "s/-//g"`
#if [[ $http == "curl" ]]
#then 
#    curl https://www.nikhef.nl/~h24/qcdnum-files/download/qcdnum${qcdnumstripver}.tar.gz > qcdnum${qcdnumstripver}.tar.gz 2>> $CURRENTDIR/install.log
#else
#    wget https://www.nikhef.nl/~h24/qcdnum-files/download/qcdnum${qcdnumstripver}.tar.gz >> $CURRENTDIR/install.log 2>&1
#fi

ln -s ${SCRIPT_DIR}/qcdnum${qcdnumstripver}.tar.gz .

tar xfz qcdnum${qcdnumstripver}.tar.gz  >> $CURRENTDIR/install.log  2>&1
cd qcdnum-${qcdnumver}

./configure --prefix=$CURRENTDIR/deps/qcdnum  >> $CURRENTDIR/install.log  2>&1
export PATH=$CURRENTDIR/deps/qcdnum/bin/:$PATH

if [[ $? != 0 ]]
then
    echo "Error, check install.log for details"
    exit
fi
make -j 8 install  >> $CURRENTDIR/install.log  2>&1
if [[ $? != 0 ]]
then
    echo "Error, check install.log for details"
    exit
fi
cd - >& /dev/null

cd $CURRENTDIR

#make a setup run enviroment script
echo "export CURRENTDIR=`pwd`" >> setup.sh
echo export LD_LIBRARY_PATH=\$CURRENTDIR/deps/qcdnum/lib/:\$LD_LIBRARY_PATH >> setup.sh
echo "export PATH=$CURRENTDIR/deps/qcdnum/bin:\$PATH" >> setup.sh
