find_program(qcdnum-config qcdnum-config PATHS ${CMAKE_SOURCE_DIR}/deps/qcdnum/bin)
if(EXISTS "${qcdnum-config}")
	set(QCDNUM_FOUND 1)
	execute_process(COMMAND ${qcdnum-config} --libdir OUTPUT_VARIABLE QCDNUM_LIBRARY_DIRS OUTPUT_STRIP_TRAILING_WHITESPACE)
	execute_process(COMMAND ${qcdnum-config} --incdir OUTPUT_VARIABLE QCDNUM_INCLUDE_DIRS OUTPUT_STRIP_TRAILING_WHITESPACE)
	add_library(QCDNUM SHARED IMPORTED)
	set_target_properties(QCDNUM PROPERTIES IMPORTED_LOCATION "${QCDNUM_LIBRARY_DIRS}/libQCDNUM.so")
	set_target_properties(QCDNUM PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${QCDNUM_INCLUDE_DIRS}/")
else()
	set(QCDNUM_FOUND 0)
endif()
if(NOT QCDNUM_FOUND AND QCDNUM_FIND_REQUIRED)
  message(FATAL_ERROR "QCDNUM not found")
endif()
