find_package(PkgConfig REQUIRED)
pkg_check_modules(yaml-cpp REQUIRED QUIET yaml-cpp)
if(yaml-cpp_FOUND)
  add_library(yaml-cpp SHARED IMPORTED)
  set_target_properties(yaml-cpp PROPERTIES IMPORTED_LOCATION "${yaml-cpp_LIBRARY_DIRS}/lib${yaml-cpp_LIBRARIES}.so")
  set_target_properties(yaml-cpp PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${yaml-cpp_INCLUDE_DIRS}")
endif()
if(NOT yaml-cpp_FOUND AND yaml-cpp_FIND_REQUIRED)
  message(FATAL_ERROR "yaml-cpp not found")
endif()
