find_program(apfelxx-config apfelxx-config PATHS ${CMAKE_SOURCE_DIR}/deps/apfelxx/bin)
if(EXISTS "${apfelxx-config}")
  set(APFELxx_FOUND 1)
  execute_process(COMMAND ${apfelxx-config} --version OUTPUT_VARIABLE APFELxx_VERSION OUTPUT_STRIP_TRAILING_WHITESPACE)
  execute_process(COMMAND ${apfelxx-config} --prefix OUTPUT_VARIABLE APFELxx_PREFIX OUTPUT_STRIP_TRAILING_WHITESPACE)
  execute_process(COMMAND ${apfelxx-config} --libdir OUTPUT_VARIABLE APFELxx_LIBRARY_DIRS OUTPUT_STRIP_TRAILING_WHITESPACE)
  execute_process(COMMAND ${apfelxx-config} --incdir OUTPUT_VARIABLE APFELxx_INCLUDE_DIRS OUTPUT_STRIP_TRAILING_WHITESPACE)
  add_library(APFELxx SHARED IMPORTED)
  if(APPLE)
    if(EXISTS "${APFELxx_LIBRARY_DIRS}/libapfelxx.dylib")
      set_target_properties(APFELxx PROPERTIES IMPORTED_LOCATION "${APFELxx_LIBRARY_DIRS}/libapfelxx.dylib")
    else()
      set_target_properties(APFELxx PROPERTIES IMPORTED_LOCATION "${APFELxx_LIBRARY_DIRS}/libapfelxx.a")
    endif()
  endif()
  if(UNIX AND NOT APPLE)
    if(EXISTS "${APFELxx_LIBRARY_DIRS}/libapfelxx.so")
      set_target_properties(APFELxx PROPERTIES IMPORTED_LOCATION "${APFELxx_LIBRARY_DIRS}/libapfelxx.so")
    else()
      set_target_properties(APFELxx PROPERTIES IMPORTED_LOCATION "${APFELxx_LIBRARY_DIRS}/libapfelxx.a")
    endif()
  endif()
  set_target_properties(APFELxx PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${APFELxx_INCLUDE_DIRS}/")
else()
  set(APFELxx_FOUND 0)
endif()
if(NOT APFELxx_FOUND AND APFELxx_FIND_REQUIRED)
  message(FATAL_ERROR "APFELxx not found")
endif()
if(NOT APFELxx_FIND_QUIETLY)
  if(APFELxx_FOUND)
    message(STATUS "Found APFELxx ${APFELxx_VERSION}: ${APFELxx_PREFIX}")
  else()
    message(STATUS "APFELxx not found")
  endif()
endif()
