#if(APPLgrid_FOUND)
  #return()
#endif()
find_program(applgrid-config applgrid-config PATHS ${CMAKE_SOURCE_DIR}/deps/applgrid/bin)
if(EXISTS "${applgrid-config}")
  set(APPLgrid_FOUND 1)
  execute_process(COMMAND ${applgrid-config} --version OUTPUT_VARIABLE APPLgrid_VERSION OUTPUT_STRIP_TRAILING_WHITESPACE)
  execute_process(COMMAND ${applgrid-config} --prefix OUTPUT_VARIABLE APPLgrid_PREFIX OUTPUT_STRIP_TRAILING_WHITESPACE)
  execute_process(COMMAND ${applgrid-config} --libdir OUTPUT_VARIABLE APPLgrid_LIBRARY_DIRS OUTPUT_STRIP_TRAILING_WHITESPACE)
  execute_process(COMMAND ${applgrid-config} --cxxflags OUTPUT_VARIABLE APPLgrid_COMPILE_OPTIONS OUTPUT_STRIP_TRAILING_WHITESPACE)
  separate_arguments(APPLgrid_COMPILE_OPTIONS UNIX_COMMAND ${APPLgrid_COMPILE_OPTIONS}) #convert space-separated list of compiler flags into a ';'-separated cmake list
  add_library(APPLgrid SHARED IMPORTED)
  if(APPLE)
    set_target_properties(APPLgrid PROPERTIES IMPORTED_LOCATION "${APPLgrid_LIBRARY_DIRS}/libAPPLgrid.dylib")
  endif()
  if(UNIX AND NOT APPLE)
    set_target_properties(APPLgrid PROPERTIES IMPORTED_LOCATION "${APPLgrid_LIBRARY_DIRS}/libAPPLgrid.so")
  endif()
  set_target_properties(APPLgrid PROPERTIES INTERFACE_COMPILE_OPTIONS "${APPLgrid_COMPILE_OPTIONS}")
else()
  set(APPLgrid_FOUND 0)
endif()
if(NOT APPLgrid_FIND_QUIETLY)
  if(APPLgrid_FOUND)
    message(STATUS "Found APPLgrid ${APPLgrid_VERSION}: ${APPLgrid_PREFIX}")
  else()
    message(STATUS "APPLgrid not found")
  endif()
endif()
