find_program(lhapdf-config lhapdf-config PATHS ${CMAKE_SOURCE_DIR}/deps/lhapdf/bin)
if(EXISTS "${lhapdf-config}")
  set(LHAPDF_FOUND 1)
  execute_process(COMMAND ${lhapdf-config} --version OUTPUT_VARIABLE LHAPDF_VERSION OUTPUT_STRIP_TRAILING_WHITESPACE)
  execute_process(COMMAND ${lhapdf-config} --prefix OUTPUT_VARIABLE LHAPDF_PREFIX OUTPUT_STRIP_TRAILING_WHITESPACE)
  execute_process(COMMAND ${lhapdf-config} --libdir OUTPUT_VARIABLE LHAPDF_LIBRARY_DIRS OUTPUT_STRIP_TRAILING_WHITESPACE)
  execute_process(COMMAND ${lhapdf-config} --incdir OUTPUT_VARIABLE LHAPDF_INCLUDE_DIRS OUTPUT_STRIP_TRAILING_WHITESPACE)
  add_library(LHAPDF SHARED IMPORTED)
  if(APPLE)
    set_target_properties(LHAPDF PROPERTIES IMPORTED_LOCATION "${LHAPDF_LIBRARY_DIRS}/libLHAPDF.dylib")
  endif()
  if(UNIX AND NOT APPLE)
    set_target_properties(LHAPDF PROPERTIES IMPORTED_LOCATION "${LHAPDF_LIBRARY_DIRS}/libLHAPDF.so")
  endif()
  set_target_properties(LHAPDF PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${LHAPDF_INCLUDE_DIRS}/")
else()
  set(LHAPDF_FOUND 0)
endif()
if(NOT LHAPDF_FIND_QUIETLY)
  if(LHAPDF_FOUND)
    message(STATUS "Found LHAPDF ${LHAPDF_VERSION}: ${LHAPDF_PREFIX}")
  else()
    message(STATUS "LHAPDF not found")
  endif()
endif()
