find_program(dyturbo-config dyturbo-config PATHS ${CMAKE_SOURCE_DIR}/deps/dyturbo/bin)
if(EXISTS "${dyturbo-config}")
  set(DYTurbo_FOUND 1)
  execute_process(COMMAND ${dyturbo-config} --version OUTPUT_VARIABLE DYTurbo_VERSION OUTPUT_STRIP_TRAILING_WHITESPACE)
  execute_process(COMMAND ${dyturbo-config} --prefix  OUTPUT_VARIABLE DYTurbo_PREFIX OUTPUT_STRIP_TRAILING_WHITESPACE)
  execute_process(COMMAND ${dyturbo-config} --libdir  OUTPUT_VARIABLE DYTurbo_LIBRARY_DIRS OUTPUT_STRIP_TRAILING_WHITESPACE)
  execute_process(COMMAND ${dyturbo-config} --incdir  OUTPUT_VARIABLE DYTurbo_INCLUDE_DIRS OUTPUT_STRIP_TRAILING_WHITESPACE)
  add_library(DYTurbo SHARED IMPORTED)
  set_target_properties(DYTurbo PROPERTIES IMPORTED_LOCATION "${DYTurbo_LIBRARY_DIRS}/libdyturbo.so")
  set_target_properties(DYTurbo PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${DYTurbo_INCLUDE_DIRS}/")
  add_library(cuba SHARED IMPORTED)
  set_target_properties(cuba PROPERTIES IMPORTED_LOCATION "${DYTurbo_LIBRARY_DIRS}/../Cuba-4.2.2/libcuba.a")
else()
  set(DYTurbo_FOUND 0)
endif()
if(NOT DYTurbo_FIND_QUIETLY)
  if(DYTurbo_FOUND)
    message(STATUS "Found DYTurbo ${DYTurbo_VERSION}: ${DYTurbo_PREFIX}")
  else()
    message(STATUS "DYTurbo not found")
  endif()
endif()
