#if(APPLwrap_FOUND)
  #return()
#endif()
find_program(applwrap-config applwrap-config PATHS ${CMAKE_SOURCE_DIR}/deps/applwrap/bin)
if(EXISTS "${applwrap-config}")
  set(APPLwrap_FOUND 1)
  execute_process(COMMAND ${applwrap-config} --version OUTPUT_VARIABLE APPLwrap_VERSION OUTPUT_STRIP_TRAILING_WHITESPACE)
  execute_process(COMMAND ${applwrap-config} --prefix OUTPUT_VARIABLE APPLwrap_PREFIX OUTPUT_STRIP_TRAILING_WHITESPACE)
  execute_process(COMMAND ${applwrap-config} --libdir OUTPUT_VARIABLE APPLwrap_LIBRARY_DIRS OUTPUT_STRIP_TRAILING_WHITESPACE)
  execute_process(COMMAND ${applwrap-config} --cxxflags OUTPUT_VARIABLE APPLwrap_COMPILE_OPTIONS OUTPUT_STRIP_TRAILING_WHITESPACE)
  separate_arguments(APPLwrap_COMPILE_OPTIONS UNIX_COMMAND ${APPLwrap_COMPILE_OPTIONS}) #convert space-separated list of compiler flags into a ';'-separated cmake list
  add_library(APPLwrap SHARED IMPORTED)
  if(APPLE)
    set_target_properties(APPLwrap PROPERTIES IMPORTED_LOCATION "${APPLwrap_LIBRARY_DIRS}/libapplwrap.dylib")
  endif()
  if(UNIX AND NOT APPLE)
    set_target_properties(APPLwrap PROPERTIES IMPORTED_LOCATION "${APPLwrap_LIBRARY_DIRS}/libapplwrap.so")
  endif()
  set_target_properties(APPLwrap PROPERTIES INTERFACE_COMPILE_OPTIONS "${APPLwrap_COMPILE_OPTIONS}")
else()
  set(APPLwrap_FOUND 0)
endif()
if(NOT APPLwrap_FIND_QUIETLY)
  if(APPLwrap_FOUND)
    message(STATUS "Found APPLwrap ${APPLwrap_VERSION}: ${APPLwrap_PREFIX}")
  else()
    message(STATUS "APPLwrap not found")
  endif()
endif()
