find_program(hoppet-config hoppet-config PATHS ${CMAKE_SOURCE_DIR}/deps/apfelxx/bin)
if(EXISTS "${hoppet-config}")
  set(Hoppet_FOUND 1)
  execute_process(COMMAND ${hoppet-config} --prefix OUTPUT_VARIABLE Hoppet_PREFIX OUTPUT_STRIP_TRAILING_WHITESPACE)
  execute_process(COMMAND ${hoppet-config} --libs   OUTPUT_VARIABLE Hoppet_LIBRARY OUTPUT_STRIP_TRAILING_WHITESPACE)
  add_library(Hoppet SHARED IMPORTED)

  set_target_properties(Hoppet PROPERTIES IMPORTED_LOCATION "${Hoppet_PREFIX}/lib/libhoppet_v1.a")

  set_target_properties(Hoppet PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${Hoppet_PREFIX}/include/")
else()
  set(Hoppet_FOUND 0)
endif()
if(NOT Hoppet_FOUND AND Hoppet_FIND_REQUIRED)
  message(FATAL_ERROR "Hoppet not found")
endif()
if(NOT Hoppet_FIND_QUIETLY)
  if(Hoppet_FOUND)
    message(STATUS "Found Hoppet ${Hoppet_VERSION}: ${Hoppet_PREFIX}")
  else()
    message(STATUS "Hoppet not found")
  endif()
endif()
