find_package(PkgConfig REQUIRED)
pkg_check_modules(yaml-cpp QUIET yaml-cpp)
if(yaml-cpp_FOUND)
  set(yaml-cpp_SO "lib${yaml-cpp_LIBRARIES}.so")
  find_library(yaml-cpp_IMPORTED_LOCATION ${yaml-cpp_SO} HINTS "${yaml-cpp_LIBRARY_DIRS}")
  if(EXISTS ${yaml-cpp_IMPORTED_LOCATION})
    add_library(yaml-cpp SHARED IMPORTED)
    set_target_properties(yaml-cpp PROPERTIES IMPORTED_LOCATION "${yaml-cpp_IMPORTED_LOCATION}")
    set_target_properties(yaml-cpp PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${yaml-cpp_INCLUDE_DIRS}")
  else()
    message(WARNING "yaml-cpp found by pkg-config, but the actual library file \"${yaml-cpp_SO}\" could not be found")
    set(yaml-cpp_FOUND 0)
  endif()
endif()
if(NOT yaml-cpp_FOUND AND yaml-cpp_FIND_REQUIRED)
  message(FATAL_ERROR "yaml-cpp not found")
endif()
if(NOT yaml-cpp_FIND_QUIETLY)
  message(STATUS "Found yaml-cpp ${yaml-cpp_VERSION}: ${yaml-cpp_IMPORTED_LOCATION}")
endif()
